### ISSUE TITLE
Sound, Bluetooth, and Backlight control doesn't work on GPD Pocket 1

### ISSUE THREAD

**Issue by 256x** [KeithIMyers/overlay-gpdpocket#13]
download .img at https://kmyers.me/chromiumos/chromiumos-for-the-gpd-pocket-1/
and flash USB memory and boot, install it.

**Comment by KeithIMyers** [comment]
Hello,
You may need to update your BIOS to the Ubuntu Bios - http://gpd.hk/gpdpocketfirmware

**Comment by 256x** [comment]
umm...I already changed it.

**Comment by gashimax** [comment]
Hello.
I updated BIOS and installed ChromiumOS, but I'm in the same state.

My state of GPD pocket 1 is bellow:
  BIOS Versiion: 2.17.1249
  ChromiumOS Version: 13047.0.2020_04_18_2142 (Developer Build-kmyers) developer-build gpdpocket) SN:nonchrome-Default string

Is there any problem? Please give me advice.

**Comment by akihitoh** [comment]
I also had the same issue. I think that I could fix sound.

The several files are missing to play audio in GPD Pocket 1.
Please copy the following folders into /usr/share/alsa/ucm from alsa-lib-1.1.9.tar.bz2
- src/conf/ucm/codecs
- src/conf/ucm/gpd-win-pocket-rt5645
- src/conf/ucm/platforms
- src/conf/ucm/chtrt5645-mono-speaker-analog-mic

**Comment by 256x** [comment]
thank you for your advice,
I will try it later and report.

**Comment by 256x** [comment]
I copied it, but don't work...
and I try to volume up, but it's change volume to 0 automatically.

**Comment by KeithIMyers** [comment]
This has been corrected in https://kmyers.me/blog/chromiumos-for-gpd-pocket/chromiumos-for-gpd-pocket-1-and-2-r89-13613-released-major-update/
