### ISSUE TITLE
Display scaling not working >80%

### ISSUE THREAD

**Issue by jibsaram** [KeithIMyers/overlay-gpdpocket#2]
Adjusting the scaling option under Display resets the default scaling that was set by default and makes me unable to switch back to it. I am only able to set it up to 80%. Changing it to anything beyond 80% does nothing to actually change the scaling. 80%, 70%, 60% and 44% all seem to work fine, with only 80% showing an incorrect (_Looks like NaN x NaN_) resolution-equivalent.

Device: Pocket 2 m3-8100Y
Version: 12249.0.2019_06_04_1701

**Comment by KeithIMyers** [comment]
This has been resolved on https://kmyers.me/blog/chromiumos-for-gpd-pocket/chromiumos-for-gpd-pocket-1-and-2-r89-13613-released-major-update/
