### ISSUE TITLE
Disabling guest account not working

### ISSUE THREAD

**Issue by jibsaram** [KeithIMyers/overlay-gpdpocket#3]
When attempting to disable the guest account, the toggle button refuses to switch to the "off" position.

Device: Pocket 2 m3-8100Y
Version: 12249.0.2019_06_04_1701

**Comment by KeithIMyers** [comment]
This has been corrected with https://kmyers.me/blog/chromiumos-for-gpd-pocket/chromiumos-for-gpd-pocket-1-and-2-r89-13613-released-major-update/
