### ISSUE TITLE
Can't login with non-google google account

### ISSUE THREAD

**Issue by gcharlie** [KeithIMyers/overlay-gpdpocket#7]
I work for Boston University and I can use my BU email address to access google apps and services. Usually If I log into google with my @bu.edu email address, the login screen will throw to a BU login screen for authentication. But on the ChromeOS install it just gives me an error. Is this normal?

**Comment by KeithIMyers** [comment]
Good Morning,
I have honestly not tested this with Managed GSuite Accounts, There is an option for "Enterprise Enrollment" on the initial setup screen, can you try that and let me know if it works.

**Comment by priceb4** [comment]
I am using a Managed GSuite account without any issues.  However, I am using google as the authentication provider.  It sounds like Boston University is using single sign on.

**Comment by gcharlie** [comment]
I've already set the notebook up with my regular Gmail account, I don't see The Enterprise option when adding a second user. Should I reinstalling and lead with the BU account, or is there another way?

**Comment by KeithIMyers** [comment]
Sorry for the delay, from my understanding, enterprise enrollment needs to be done on the initial setup and be the first account on the device. I am not sure of a way to bypass this limitation. I have been able to test this on a non-gmail GSuite account and it seems to be working.

**Comment by gcharlie** [comment]
seems like enterprise enrollment doesn't work in my case either, seems to have the same result; never gets kicked over to BU's login page. I haven't used other chrome books but maybe this is the case with all of them. I am able to use my BU GSuite account but only in incognito mode where the whole login process stays in the browser. feel free to close if this isn't specific enough to the project.

**Comment by KeithIMyers** [comment]
Hello,
This should be fixed in https://kmyers.me/blog/chromiumos-for-gpd-pocket/chromiumos-for-gpd-pocket-1-and-2-r89-13613-released-major-update/
