### ISSUE TITLE
unable to play encrypted streaming videos on GPD Pocket 2

### ISSUE THREAD

**Issue by markzhangdo** [KeithIMyers/overlay-gpdpocket#8]
Unable to play videos from Netflix, Hulu, HBO go.  

Occasionally I will also get errors on Youtube that state "Your browser does not support this video format"

**Comment by KeithIMyers** [comment]
Thank you for your report. Currently the build does not support Widevine DRM protected content. I am working to a workaround to allow users to install the widevine plugins
